version: '3.8'

services:
  battleship-game:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    volumes:
      - .:/app
      - /app/node_modules
